### ISSUE TITLE
Not working in AWS VPC

### ISSUE THREAD

**Issue by khuongduybui** [willemmulder/Diont#4]
Hello, it's me again :D

This time I'm trying an all-virtual setup in AWS where I have a VPC with:
- IP range 10.0.0.0/16
- Network ACL allowing ALL traffic
- Default subnet 10.0.0.0/24
- 2 EC2 instances (running node 4.4.4 on Ubuntu 14.04 server) with a Security Group allowing ALL traffic within 10.0.0.0/16

When I run listeners_broadcast, server_1, and server_3 on both instances, each listener only detects servers on its own instance.
The detected host IP (when unspecified, as in server_3) is indeed the 10.0.0.0/32 IP though, not 127.0.0.1.

**Comment by willemmulder** [comment]
I must admit I've never done anything with virtual networks :-) Could you give me the service JSONs that you put into the various `diont.announceService(service);` ?

**Comment by khuongduybui** [comment]
The exact code in your examples folder. The only change I make is require('../diont') => require('diont')

**Comment by willemmulder** [comment]
I know this is long ago... And sorry I didn't manage to help. Did you get it working by any chance?

**Comment by khuongduybui** [comment]
Nope.

**Comment by khuongduybui** [comment]
AWS doesn't support multicast or broadcast protocols. Closing this issue.

(See: https://aws.amazon.com/vpc/faqs/#Routing_and_Topology)

**Comment by willemmulder** [comment]
Thanks for coming back on this! 👍 

Too bad AWS doesn't support it. Hope you got what you want using some other method/workaround?
