### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by kennarddh** [willemmulder/Diont#5]

**Comment by willemmulder** [comment]
Good idea; feel free to create a PR and I'll merge it!

**Comment by kennarddh** [comment]
Should I rewrite the lib or create dts file?

**Comment by willemmulder** [comment]
I'd say that the best option would be to rewrite it in Typescript, then export the JS file and types to a /lib folder, and ensure that that is used when publishing to NPM. I just found this guide that has the same idea: https://itnext.io/step-by-step-building-and-publishing-an-npm-typescript-package-44fe7164964c. Would that work?

**Comment by kennarddh** [comment]
Ok. I'll try it.

**Comment by kennarddh** [comment]
What is the use of the `toString` function?

```js
const socket = dgram.createSocket({
	type: 'udp4',
	reuseAddr: true,
	toString: function () {
		return 'udp4'
	},
})
```

Typescript throw error because `toString` doesn't exist in `dgram.createSocket` options

**Comment by willemmulder** [comment]
Wow, amazing work on the PR! 
I have time on friday to look at it, test it and hopefully merge it.
Thanks so far; it's appreciated!

**Comment by willemmulder** [comment]
Quick update: it's going to be tomorrow. Too much going on today :-)

I'll let you know!

**Comment by willemmulder** [comment]
As mentioned on the PR: looks good; thanks for the effort and the nice optimizations/cleanups here and there!
I'll publish in a minute.

**Comment by willemmulder** [comment]
Just published!
